name: Trips CICD

env:
  registry: docker.pkg.github.com
  repository: cdanvergara/oh-devops
  docker_path: apis/trips
  staging_url: https://openhackmlm47ad5trips-staging.azurewebsites.net
  prod_url: https://openhackmlm47ad5trips.azurewebsites.net
  resource_group: openhackmlm47ad5rg
  webapp_name: openhackmlm47ad5trips
  build_name: Trips
  webv_path: apis/trips/webvalidate

on:
  push:
    branches: [ main ]
    paths: 
      - apis/trips/**  
      - .github/workflows/trips.yml
  pull_request:
    branches: [ main ]
    paths: 
      - apis/trips/**
      - .github/workflows/trips.yml

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/trips    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2.0.3
      with:
        go-version: 1.12

    - name: Install dependencies
      run: go get

    - name: Run Unit Tests
      run: go test ./tests

    - uses: actions/github-script@0.9.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });
