name: User Profile CICD

env:
  registry: docker.pkg.github.com
  repository: cdanvergara/oh-devops
  docker_path: apis/userprofile
  staging_url: https://openhackmlm47ad5userprofile-staging.azurewebsites.net
  prod_url: https://openhackmlm47ad5userprofile.azurewebsites.net
  resource_group: openhackmlm47ad5rg
  webapp_name: openhackmlm47ad5userprofile
  build_name: User Profile
  webv_path: apis/userprofile/webvalidate

on:
  push:
    branches: [ main ]
    paths: 
      - apis/userprofile/**  
      - .github/workflows/userprofile.yml
  pull_request:
    branches: [ main ]
    paths: 
      - apis/userprofile/**
      - .github/workflows/userprofile.yml

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/userprofile    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test

    - uses: actions/github-script@0.9.0
      if: failure()
      with:
        github-token: ${{secrets.TOKEN}}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });

